### ISSUE TITLE
Various issues building the `G` editor ... 

### ISSUE THREAD

**Issue by johnsonjh** [tkchia/gcc-ia16#113] opened 2022-06-16 04:34 UTC
Trying to build [`G`](https://github.com/johnsonjh/g) with IA16-GCC is giving me some issues - perhaps the problems are mine?

Building `FULL_G` crashes the compiler when using `-O2` or `-Os`, but `-O1` is OK:
```
» ~/src/build-ia16/prefix/bin/ia16-elf-gcc -march=i8086 -mregparmcall -mcmodel=medium -UDOS -DUNIX=1 -DFULL_G=1 -O2 -D_FORTIFY_SOURCE=2 -Wno-int-to-pointer-cast g.c -o g.exe -lpdcurses -li86
g.c: In function ‘Drive’:
g.c:15801:1: internal compiler error: in elimination_costs_in_insn, at reload1.c:3624
 }
 ^
unrecognized DWARF version in .debug_info at 6
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://gcc.gnu.org/bugs.html> for instructions.
```

The resulting binary, however, doesn't work (at least not in emu2, but also tested a bit back on a real system with the same results):

```
» emu2 g.exe -v
G 
Illegal or missing delimiter.
```

This is likely due to memory model issues, I assume, or I'm running out of stack space ... FULL_G usually takes about 128K-130K of memory - however, compiling a TINY_G binary (~112K) has similar problems, and the LINE_G (which works fine on 32K systems) also behaves strangely, seemingly getting stray "M"s (`^M`?) in the input?

```
» emu2 g.exe -{
{ 5+5

Syntax error in expression.
Culprit: M

{ }
Empty file.
EOF
axcM

Illegal or missing delimiter.
Culprit: xcMM

Empty file.
EOF
a

Illegal or missing delimiter.
Culprit: M

Empty file.
EOF
*
```

The behavior is the same with the most minimal `LINE_G` build, no libi86 or curses used:

```
» ~/src/build-ia16/prefix/bin/ia16-elf-gcc -march=i8086 -mregparmcall -mcmodel=medium -DOS=1 -UUNIX -DLINE_G=1 -O1 -U_FORTIFY_SOURCE -Wno-int-to-pointer-cast g.c -o g.exe      

» ls -la g.exe
.rwxr-xr-x jhj jhj 120 KB Thu Jun 16 00:28:10 2022 g.exe*

» emu2 g.exe -v
Line-mode G 4.7.4-dev (2022-05-17)

» emu2 g.exe -{
{ 5+5

Syntax error in expression.
Culprit: M

{ }
Empty file.
EOF
xaV

Illegal endpoint.
Culprit: VM

Empty file.
EOF
q

Verb not recognised.
Culprit: M

Empty file.
EOF
*                                                                                                                    
```

I'm using a build from git - 704204f10b7095d3cd75276925ef48565cfb3225 - on a Fedora 36 x86_64 system.

Hopefully, it's just something I'm doing wrong.

**Comment by tkchia** [comment] 2022-06-16 17:43
Hello @johnsonjh,

> Trying to build [G](https://github.com/johnsonjh/g) with IA16-GCC is giving me some issues - perhaps the problems are mine?
> 
> Building FULL_G crashes the compiler when using `-O2` or `-Os`, but `-O1` is OK:

Definitely a bug in `gcc-ia16` (the compiler should _not_ crash, ever).  Let me look further into this.  Apparently the compiler has a problem matching an internally generated RTL instruction to an instruction template:
```
(insn 1250 557 1199 69 (parallel [
            (set (mem/c:HI (symbol_ref:HI ("show_template") [flags 0x2]
                    <var_decl 0x7f57492d6f30 show_template>) [3 show_template+0 S2 A16])
                (plus:HI (minus:HI (reg/v:HI 200 [ level ])
                        (eq:HI (reg:CCZ_C 14 cc)
                            (const_int 0 [0])))
                    (const_int 0 [0])))
            (clobber (reg:CC 14 cc))
        ]) g.c:15758 -1
     (expr_list:REG_DEAD (reg:CCZ_C 14 cc)
        (expr_list:REG_UNUSED (reg:CC 14 cc)
            (nil))))
```
This was with the build command
```
$ make V=1 LINE_G=1 CC='ia16-elf-gcc -DDOS -mcmodel=medium' OPTFLAGS=-Os
```

---

> The resulting binary, however, doesn't work (at least not in emu2, but also tested a bit back on a real system with the same results):

I could not reproduce this:
```
$ make V=1 LINE_G=1 CC='ia16-elf-gcc -DDOS -mcmodel=medium -mregparmcall' OPTFLAGS=-O1
...
$ mv g g.exe
$ dosemu -tde -quiet -K . -E 'g.exe -v'
Line-mode G 4.7.4-dev (2022-05-17)
```

Thank you!

**Comment by tkchia** [comment] 2022-06-16 21:33
Hello @johnsonjh,

The compiler crash should be fixed now with `gcc-ia16` commit https://github.com/tkchia/gcc-ia16/commit/c763cb6e365eee543c812435354e0cba7d61e235 .  Thank you!

**Comment by johnsonjh** [comment] 2022-06-16 21:34
@tkchia Thanks.

I'll update my toolchain and try again.  If there are any issues I'll open a new ticket.

**Closed as completed** 2022-06-16 21:34 UTC
Labels: bug

**Comment by tkchia** [comment] 2022-06-16 21:40
Hello @johnsonjh,

On the `Culprit: M` problem &mdash; yes, it is due to stray `^M` characters.  The `newlib-ia16` library used by the `build-ia16` toolchain filters away CR characters from CR-LF only at the `stdio` level (i.e. `fopen`, `fclose`, `printf`, `scanf`, etc.), and not at the lower level of file descriptors (i.e. `open`, `close`, `read`, `write`, etc.).  Classical MS-DOS compilers filter away CR characters at the file descriptor level.

So you probably need to modify the relevant parts of the source to look for CR's in addition to `LFEED` characters.  (You only have to do this for the MS-DOS-specific portions.)

Tank you!
