### ISSUE TITLE
Segmentation fault when compiling with -O

### ISSUE THREAD

**Issue by bartoldeman** [tkchia/gcc-ia16#5] opened 2017-11-08 00:27 UTC
```
$ cat tst4.c
void scan(int __far *p)
{
  for(; *p; p++);
}
$ ia16-elf-gcc -O -I../hdr -c tst4.c
tst4.c: In function ‘scan’:
tst4.c:4:1: internal compiler error: Segmentation fault
 }
 ^
0x856168a crash_signal
        ../../gcc-ia16/gcc/toplev.c:333
0x8882ea7 try_combine
        ../../gcc-ia16/gcc/combine.c:4319
0x888511c combine_instructions
        ../../gcc-ia16/gcc/combine.c:1267
0x888511c rest_of_handle_combine
        ../../gcc-ia16/gcc/combine.c:14368
0x888511c execute
        ../../gcc-ia16/gcc/combine.c:14411
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.
```

Thanks to your fix to issue 3 I can compile a lot without optimizations enabled but as soon as I do enable them I get issues. This is the smallest segmentation fault example I could produce.

**Comment by tkchia** [comment] 2017-11-10 20:38
Hello @bartoldeman,

This issue turns out to have the same root cause as https://github.com/tkchia/gcc-ia16/issues/2 --- so I am also closing it.  Thanks!

**Closed as completed by tkchia** 2017-11-10 20:38 UTC
